### ISSUE TITLE
Progress indicator during form submission

### ISSUE THREAD

**Issue by nathanfletcher** [lacabra/submission-digitalpublicgoods#90] opened 2021-12-15 14:43 UTC
### Issue description
There is currently no progress indicator in the form much like the way there in in the eligibility form

### Steps to reproduce the issue

1.
2.
3.

### What's the expected result?
As the form is being filled, the progress indicator should give visual feedback on how far along the submitter has gone.

### Additional details

- What browser did this occur on?
- What operating system did this occur on?
-

### (Optional) Screenshot

![Screenshot 2021-12-15 at 2 43 14 PM](https://user-images.githubusercontent.com/1917416/146207288-494e259b-30bd-4ac4-8887-bcefb1c9de1d.png)

**Comment by lacabra** [comment] 2021-12-15 17:57
Marking as duplicate of #23 and closing. Reopen if you disagree @nathanfletcher

**Closed by lacabra** 2021-12-15 17:57 UTC
Labels: enhancement
